documentation/urls.py
from django.conf.urls import url
from django.urls import include, path

from . import views


app_name = 'documentation'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article/(?P<address>\w+)/(?P<lang>\w+)?$', views.ArticleView.as_view(), name='article_page'),
    url(r'^article_search$', views.article_search, name='article_search'),
    url(r'^article_page_404$', views.article_404, name='article_404'),
    url(r'^typo_feedback$', views.error_send_email, name='error_send_email'),
    url(r'^pdf_creator/(?P<lang>\w+)$', views.pdf_creator, name='pdf_creator'),
]

urlpatterns += [
    path('i18n/', include('django.conf.urls.i18n')),
    url(r'^change_version/(?P<version>\w+)$', views.change_version, name='change_version'),
]

make_the_docs/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('docs/', include('documentation.urls')),
    path('tinymce/', include('tinymce.urls')),
]

from django.views.generic import RedirectView

urlpatterns += [
    path('', RedirectView.as_view(url='/docs/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documentation/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from tinymce.models import HTMLField


LANG_STATUS = (
        ('ru', 'russian'),
        ('en', 'english'),
    )


class Article(models.Model):
    section = models.ForeignKey('Section', on_delete=models.SET_NULL, null=True, blank=True)
    priority = models.SmallIntegerField(default=0, null=True, blank=True)
    address = models.CharField(max_length=30, null=True, blank=True)
    version = models.SmallIntegerField(default=None, null=True, blank=True)

    def __str__(self):
        return self.address

    def get_absolute_url(self):
        return reverse('documentation:article_page', args=[self.address])

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.version is not None:
            if self.version not in [item.version for item in Article.objects.filter(address=self.address)]:
                article_latest = Article.objects.create(section=self.section, priority=self.priority, address=self.address)
                for item in self.content.all():
                    ArticlesContent.objects.create(article=article_latest, title=item.title, body=item.body, language=item.language)
        return super(Article, self).save()

    class Meta:
        ordering = ['-priority']
        verbose_name = _('Article')
        verbose_name_plural = _('Articles')


class ArticlesContent(models.Model):
    article = models.ForeignKey('Article', on_delete=models.CASCADE, related_name='content', null=True, blank=True)
    title = models.CharField(max_length=100, help_text="Enter a titles article")
    body = HTMLField(help_text="Enter a text article")
    language = models.CharField(max_length=2, choices=LANG_STATUS, default='en', help_text='check language')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('documentation:article_page', args=[self.article, self.language])

    class Meta:
        ordering = ['-article__priority']
        verbose_name = _('ArticlesContent')
        verbose_name_plural = _('ArticlesContents')


class Section(models.Model):
    title = models.CharField(max_length=30, help_text="Enter a sections of articles")
    priority = models.SmallIntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-priority']
        verbose_name = _('Section')
        verbose_name_plural = _('Sections')


class SectionContent(models.Model):
    section = models.ForeignKey('Section', on_delete=models.CASCADE, related_name='content', null=True, blank=True)
    name = models.CharField(max_length=100, help_text="Enter a section name")
    language = models.CharField(max_length=2, choices=LANG_STATUS, default='en', help_text='check language')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-section__priority']
        verbose_name = _('SectionContent')
        verbose_name_plural = _('SectionsContents')

documentation/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _


class ErrorForm(forms.Form):
    err_name = forms.CharField(label=_('Name'), help_text=_('Enter a message name'), max_length=50, )
    err_desc = forms.CharField(label=_('Description'), help_text=_('Describe the error'), max_length=1000, widget=forms.Textarea(attrs={'rows': 4}))
    

class SearchForm(forms.Form):
    search_key = forms.CharField(label=_('Search by'), help_text=_('Enter a search term'), max_length=30, )

documentation/views.py
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import redirect, render
from django.template.loader import get_template
from django.views import generic
from io import BytesIO
from xhtml2pdf import pisa

from .forms import ErrorForm, SearchForm
from .models import Article, ArticlesContent, SectionContent
from .utils import add_anchor, get_anchor_list, get_search_context, fetch_pdf_resources, search_formatting
from make_the_docs import settings


def index(request):
    article = ArticlesContent.objects.filter(article__version=request.session.get('content_version', None)).order_by('-article__section__priority').first()
    if not article:
        return redirect('/docs/article_page_404', permanent=True)
    return redirect(f'/docs/article/{article.article.address}')


class ArticleView(generic.DetailView):
    model = Article
    template_name = 'index.html'
    slug_field = 'address'
    slug_url_kwarg = 'address'

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            return redirect('/docs/article_page_404', request=None, permanent=True)

    def get_queryset(self):
        self.queryset = Article.objects.filter(version=self.request.session.get('content_version', None))
        return self.queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            article = self.object.content.filter(language=self.kwargs['lang']).first()
        except:
            article = self.object.content.filter(language=self.request.LANGUAGE_CODE).first()
        if article is None:
            article = self.object.content.filter(language=settings.LANGUAGE_CODE).first()
        article.body = add_anchor(article.body)
        context.update({
            'title': article.title,
            'body': article.body,
            'anchor_list': get_anchor_list(article.body),
        })
        return super().get_context_data(**context)


def article_404(request):
    return render(
        request,
        'article_404.html'
    )


def article_search(request):
    form = SearchForm(request.POST)
    if not form.is_valid():
        return HttpResponseRedirect(request)
    key = form.cleaned_data.get("search_key")
    results = search_formatting(ArticlesContent.objects.filter(Q(title__icontains=key) | Q(body__icontains=key)), key=key)
    results, count_num = get_search_context(results, key=key)
    return render(
        request,
        'search_results.html',
        context={'results': results,
                 'count_num': count_num,
                 'key': key,
                 }
    )


def error_send_email(request):
    err_form = ErrorForm(request.POST)
    err_message = err_form['err_name'].value() + "\n" + err_form['err_desc'].value()
    if err_form.is_valid():
        try:
            send_mail('Make-the-docs-site', err_message, 'site@example.com', ['user@example.com'])
        except BadHeaderError:
            return HttpResponse('Invalid header found.')
        return HttpResponseRedirect('/docs/')
    else:
        return HttpResponse('Make sure all fields are entered and valid.')


def pdf_creator(request, **kwargs):
    template = get_template('pdf_creator.html')
    list_articles = ArticlesContent.objects.filter(article__version=request.session.get('content_version', None), language=kwargs['lang'])
    list_section = SectionContent.objects.filter(language=request.LANGUAGE_CODE)
    if list_section is None:
        list_section = SectionContent.objects.filter(language=settings.LANGUAGE_CODE)
    context = {
        'list_articles': list_articles,
        'list_section': list_section,
    }
    html = template.render(context)
    result = BytesIO()
    pdf = pisa.pisaDocument(html.encode('UTF-8'), result, encodind='UTF-8', link_callback=fetch_pdf_resources)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type="application/pdf")


def change_version(request, **kwargs):
    if kwargs['version'] == 'None':
        del request.session['content_version']
    else:
        request.session['content_version'] = kwargs['version']
    return HttpResponseRedirect('/docs/')

documentation/templates/article_404.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block title %}
<title>
  {% trans "Page not found" %}
</title>
{% endblock %}

{% block breadcrumb %}
<p>{% trans "Page not found" %}</p>
{% endblock %}

{% block content %}
<div class="text-center">
  <h1><i>{% trans "Requested article not found" %}</i></h1>
  <h4><i>{% trans "Maybe she was deleted" %}</i></h4>
  {% load static %}
  <img class="rounded w-50" src="{% static 'article_404.png' %}">
</div>
{% endblock %}

documentation/templates/base_generic.html
<!DOCTYPE html>

{% load i18n %}

<html lang="en">
<head>

  {% block title %}<title>Make the Docs</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
          integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
          crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
          integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
          integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
          crossorigin="anonymous"></script>

  {% load crispy_forms_tags %}
  {% load static %}

  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
  <div class="container-fluid m-md-0 p-md-0">
    <div class="row">
      <nav class="sidebar-nav col-md-3 d-none d-sm-none d-md-block">
        <div class="sidebar-nav_upper justify-content-center">
          <div class="row m-2">
            <button type="button" class="btn" data-toggle="button" aria-pressed="false">
              {% load static %}
              <img class="content_logo w-100" src="{% static 'logo.svg' %}" alt="logo">
            </button>
          </div>
          <!-- Button trigger modal -->
          <div class="form-group">
            <button type="button" class="btn btn-link w-100" data-toggle="modal" data-target="#Search-Modal">
              <input type="text" class="form-control" id="sidebar-nav_upper__search-form"
                     placeholder="Search Docs">
            </button>
          </div>
          <!-- Button trigger modal end -->
        </div>
        <!-- Sidebar sections & articles -->
        <div class="sidebar-nav_list">
          {% block sidebar %}
          {% if list_articles %}
          <ul class="list-group">
            {% for sections in list_section %}
            {% for section in sections.content.all %}
            {% if LANGUAGE_CODE in sections.lang_list and section.language == LANGUAGE_CODE or LANGUAGE_CODE not in sections.lang_list and section.language == settings.LANGUAGE_CODE %}
            <li class="sidebar-nav_list__tags list-group-item text-uppercase">{{ section }}</li>
            <ul class="list-group">
              {% for article in list_articles %}
              {% if article.section == section.section %}
              {% for item in article.content.all %}
              {% if LANGUAGE_CODE in article.lang_list %}
              {% if item.language == LANGUAGE_CODE %}
              <li><a class="list-group-item list-group-item-action text-decoration-none"
                     href="{% url 'documentation:article_page' article.address %}">{{ item.title }}</a>
              </li>
              {% endif %}
              {% elif LANGUAGE_CODE not in article.lang_list and item.language == settings.LANGUAGE_CODE %}
              <li><a class="list-group-item list-group-item-action text-decoration-none"
                     href="{% url 'documentation:article_page' article.address %}">{{ item.title }}</a>
              </li>
              {% endif %}
              {% endfor %}
              {% if article.address in request.get_full_path %}
              {% if anchor_list %}
              {% for key, value in anchor_list.items %}
              <li>
                <a class="sub-navigation list-group-item list-group-item-action pl-5"
                   href="#{{ value }}">{{ key|safe }}</a></li>
              {% endfor %}
              {% endif %}
              {% endif %}
              {% endif %}
              {% endfor %}
            </ul>
            {% endif %}
            {% endfor %}
            {% endfor %}
          </ul>
          {% endif %}
          {% endblock %}
        </div>
        <!-- Sidebar sections & articles end -->
      </nav>
      <div class="content col-md-7 ml-2">
        <div class="row">
          <div class="col-9">
            <nav aria-label="breadcrumb">
              <ol class="breadcrumb bg-white m-0 pl-0">
                <li class="breadcrumb-item"><a class="text-decoration-none"
                                               href="{% url 'documentation:index' %}">
                  {% load static %}
                  <img class="content_logo" src="{% static 'home_logo.png' %}" alt="home_logo">
                </a></li>
                <li class="breadcrumb-item active" aria-current="page">
                  {% block breadcrumb %}{% endblock %}
                </li>
              </ol>
            </nav>
          </div>
          <div class="col-3 align-self-center">
            <p class="text-right m-0"><a class="text-decoration-none"
                                         href="https://github.com/SuperLalka/make_the_docs">
              <img class="content_logo"
                   src="https://github.githubassets.com/images/spinners/octocat-spinner-128.gif"
                   alt="git_logo">
              {% trans "Edit on GitHub" %}
            </a></p>
          </div>
        </div>
        <hr>
        <!--content_start-->
        <div class="content-body">
          {% block content %}{% endblock %}
        </div>
        <!--content_end-->
        <footer class="content-footer">
          <hr>
          <h6 class="footer-text">
            © Copyright 2020, Make the Docs, LalkaInc & contributors Revision.
          </h6>
          <h6 class="footer-text">
            Built with Sphinx using a theme provided by Make the Docs.
          </h6>
          <div class="row">
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-link" data-toggle="modal" data-target="#ErrorModal">
              {% trans "Report a bug" %}
            </button>
            <button type="button" class="btn btn-link" data-toggle="modal" data-target="#PDFCreateModal">
              {% trans "Save as PDF" %}
            </button>
            <!-- Button trigger modal end -->
            <!-- Modal Error -->
            <div class="modal fade" id="ErrorModal" tabindex="-1" role="dialog"
                 aria-labelledby="ErrorModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog modal-lg">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="ErrorModalLabel">{% trans "Report a bug" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form action="/docs/typo_feedback" method="post">
                      {% csrf_token %}
                      {{ err_form|crispy }}
                      <button type="button" class="btn btn-secondary"
                              data-dismiss="modal">{% trans "Cancel" %}
                      </button>
                      <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
            <!-- Modal Search -->
            <div class="modal fade" id="Search-Modal" tabindex="-1" role="dialog"
                 aria-labelledby="Search-Modal-form"
                 aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="Search-Modal-form">{% trans "Search by" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form action="/docs/article_search" method="post">
                      {% csrf_token %}
                      {{ search_form|crispy }}
                      <button type="button" class="btn btn-secondary"
                              data-dismiss="modal">{% trans "Cancel" %}
                      </button>
                      <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
            <!-- Modal PDF Creator -->
            <div class="modal fade" id="PDFCreateModal" tabindex="-1" role="dialog"
                 aria-labelledby="PDFCreateModalLabel"
                 aria-hidden="true">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="PDFCreateModalLabel">{% trans "Сhoose language" %}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <ul class="list-group">
                      <a href="{% url 'documentation:pdf_creator' 'ru' %}"
                         class="list-group-item list-group-item-action border-0">
                        {% load static %}
                        <img class="content_logo align-baseline" src="{% static 'flag_rus.gif' %}" alt="logo">
                        {% trans "Save in Russian" %}</a>
                      <a href="{% url 'documentation:pdf_creator' 'en' %}"
                         class="list-group-item list-group-item-action border-0">
                        {% load static %}
                        <img class="content_logo align-baseline" src="{% static 'flag_eng.gif' %}" alt="logo">
                        {% trans "Save in English" %}</a>
                    </ul>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary"
                            data-dismiss="modal">{% trans "Cancel" %}
                    </button>
                  </div>
                </div>
              </div>
            </div>
            <!-- Modal end -->
          </div>
        </footer>
      </div>
    </div>
  </div>
  <div class="change-block">
    {% block content_switch %}
    <div class="btn-group d-none d-xs-none d-sm-block" role="group" aria-label="First group">
      <form action="{% url 'documentation:set_language' %}" method="post">
        <div class="form-row align-items-center justify-content-end">
          <div class="col-auto my-1">
            {% csrf_token %}
            <select name="language" class="custom-select custom-select-sm" id="inlineFormCustomSelect">
              {% get_current_language as LANGUAGE_CODE %}
              {% get_available_languages as LANGUAGES %}
              {% get_language_info_list for LANGUAGES as languages %}
              {% for language in languages %}
              <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %}selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
              </option>
              {% endfor %}
            </select>
          </div>
          <button type="submit" class="btn btn-dark btn-sm">{% trans "Change" %}</button>
        </div>
      </form>
    </div>
    <div class="btn-group d-none d-xs-none d-sm-block" role="group">
      <ul class="change_version-list list-group list-group-horizontal justify-content-end">
        {% for version in version_list %}
        {% if version|slugify != request.session.content_version|slugify %}
        <a href="{% url 'documentation:change_version' version %}">
          <button type="button" class="change_version-button btn btn-secondary btn-sm">{% if version == None %}latest{% else %}{{ version }}{% endif %}
          </button>
        </a>
        {% endif %}
        {% endfor %}
        <a href="#">
          <button type="button" class="change_version-button btn btn-secondary btn-sm visible">{% trans 'Current version is ' %}{% if request.session.content_version == None %}latest{% else %}{{ request.session.content_version }}{% endif %}
          </button>
        </a>
      </ul>
    </div>
    {% endblock %}
  </div>
</body>
</html>

documentation/templates/index.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block title %}
<title>
  {{ title }}
</title>
{% endblock %}

{% block breadcrumb %}
{{ title }}
{% endblock %}

{% block content %}
{{ body|safe }}
{% endblock %}

documentation/templates/index_reversion.html
{% extends "base_generic.html" %}


{% block title %}
<title>
  {% for item in article %}
  {{ article.object.field_dict.title }}
  {% endfor %}
</title>
{% endblock %}

{% block breadcrumb %}
{% for item in article %}
{{ item.field_dict.title }} (версия от {{ item.revision.date_created }})
{% endfor %}
{% endblock %}

{% block content %}
{% for item in article %}
{{ item.field_dict.body|safe }}
{% endfor %}
{% endblock %}

{% block versions %}
{% for version in article_versions %}
<a class="dropdown-item"
   href="{% url 'documentation:article_reversion' version.field_dict.address version.revision.id %}">{{ version.revision.date_created }}
</a>
{% endfor %}
{% endblock %}

documentation/templates/pdf_creator.html
<!DOCTYPE html>

{% load i18n %}
{% load static %}

<html lang="en">
<head>

  <title>Make the Docs</title>
  <meta charset="utf-8">
  <style>
    @font-face {
      font-family: Arial;
      src: url("{% static 'fonts/arial.ttf' %}");
    }

    body {
      font-family: Arial;
    }

    .text-center {
      text-align: center;
    }

    .section {
      font-size: 20px;
    }
  </style>

</head>

<body>
  <div>
    <hr>
    <h1 class="text-center">{% trans "Content" %}</h1>
    <ul>
      {% for section in list_section %}
      <li>{{ section }}</li>
      <ul>
        {% for article in list_articles %}
        {% if article.article.section == section.section %}
        <li><b>{{ article.title }}</b></li>
        {% endif %}
        {% endfor %}
      </ul>
      {% endfor %}
    </ul>
  </div>
  <div>
    {% for section in list_section %}
    <hr>
    <h1 class="section text-center"><b>{{ section }}</b></h1>
    {% for article in list_articles %}
    {% if article.article.section == section.section %}
    <hr>
    <h2 class="text-center">{{ article.title|safe }}</h2>
    {{ article.body|safe }}
    {% endif %}
    {% endfor %}
    {% endfor %}
  </div>
</body>
</html>

documentation/templates/pdf_maker_template.html
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{ article.title }}</title>
  <style type="text/css">
    @font-face { font-family: Arial; src: url("/PROJECTS/make_the_docs/documentation/static/fonts/arial.ttf"); }
    @font-face { font-family: Tahoma; src: url("/PROJECTS/make_the_docs/documentation/static/fonts/tahoma.ttf"); }

    *, body {
      font-family: Tahoma, Verdana, Arial, Helvetica;
      font-weight: 200;
      font-size: 14px;
    }

    .header {
      font-size: 20px;
      font-weight: 100;
      text-align: center;
      color: #007cae;
    }

    .title {
      font-size: 22px;
      font-weight: 100;
      /* text-align: right;*/
      padding: 10px 20px 0px 20px;
    }

    .title span {
      color: #007cae;
    }

    .details {
      padding: 10px 20px 0px 20px;
      text-align: left !important;
      /*margin-left: 40%;*/
    }

    .hrItem {
      border: none;
      height: 1px;
      /* Set the hr color */
      color: #333; /* old IE */
      background-color: #fff; /* Modern Browsers */
    }
  </style>
</head>
<body>
  <div class='wrapper'>
    <div class='header'>
      <p class='title'>{{ article.title }}</p>
    </div>
    <div>
      {% block content %}
      {{ article.body|safe }}
      {% endblock %}
    </div>
  </div>
</body>
</html>

documentation/templates/search_results.html
{% extends "base_generic.html" %}

{% load i18n %}

{% block title %}
<title>
  {% trans "Searching results" %}
</title>
{% endblock %}

{% block breadcrumb %}
{% trans "Found matches in article titles and texts:" %} {{ count_num }}
{% endblock %}

{% block content %}

{% if results %}
<h5 class="text-center">{% trans "Matches with" %} <b>"{{ key }}"</b> {% trans "found:" %}</h5>
{% for item in results %}
<div class="card w-100">
  <div class="card-body justify-content-center">
    <h4 class="card-title"><a href="{{ item.get_absolute_url }}">{{ item.title|safe }} ({% trans 'version - ' %}
        {% if item.article.version == None %}latest{% else %}{{ item.article.version }}{% endif %})</a></h4>
    {% if item.preamble %}
    <p class="card-text">{{ item.preamble|truncatewords_html:15|safe }}</p>
    {% endif %}
    {% for key, value in item.found.items %}
    <a href='{{ item.get_absolute_url }}#{% for k, v in item.anchor_list.items %}{% if k == key %}{{ v }}{% endif %}{% endfor %}'>
      <h5>{{ key|safe }}</h5>
    </a>
    {{ value|truncatewords_html:35|safe }}
    {% endfor %}
  </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}

{% block content_switch %}
{% endblock %}